version: "3.9"
services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: udap
      POSTGRES_PASSWORD: udap
      POSTGRES_DB: udap
  backend:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - persistant:/local
    networks:
      - default
    env_file:
      - .env
    ports:
      - "3020:3020"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "5002:5002"
volumes:
  persistant: