version: "3.9"
services:
  backend:
    build: .
    volumes:
      - persistant:/local
    env_file:
      - .env
    ports:
      - "3020:3020"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "5002:5002"
volumes:
  persistant: